id = 11
title = "CTF After Dark Kickoff"
short = "CTF After Dark" 
date = "Wednesday 3/1 6:00PM-8:00PM PT"
description = """#### ğŸ”¥Get ready to flex your cyber skills and bring your A-game to the ultimate test!ğŸ”¥ 
CTF After Dark is back and better than ever! ğŸ’­You've been training hard all quarter long and now it's time to put your knowledge to the test. ğŸ‹ï¸We've got 9ï¸âƒ£ flights of stairs worth of challenges waiting for you, all related to web hacking. ğŸ¦µğŸ¥µBut don't worry, you're an absolute unit. A Cookie ğŸª Monster ğŸ”µğŸ‘„ğŸ”µ with a megamind brain ğŸ§  ready for anything that comes your way. ğŸ™…ğŸ™…â€â™€ï¸ğŸ™…â€â™‚ï¸Come play our ğŸš© Capture the Flag (CTF) ğŸš©competition ğŸ•¸ğŸ‘¨â€ğŸ’» and show off all that you've learned from our workshops this winter. Winners ğŸ…will be rewarded ğŸ‘€, so don't miss out! Be there or be square ğŸŸ¨."""
link = ""
slides = ""
